baseURL = 'https://www.linuxdojo.co.uk'
languageCode = 'en-us'
title = 'Linuxdojo - Technical Blog and General Ramblings'
theme = 'PaperMod'

[params]
description = 'Blog and General Ramblings'
author = 'Andrew Glass'
github = 'https://github.com/andrewglass3'
